config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "departments#index"
    resources :departments do
      resources :reports
    end
    resources :reports do
      member do
        put :approve
      end
    end
    resources :relationships, only: %i(new create destroy update)
    resources :comments
    resources :notifies, only: :show
  end
  devise_for :users
  resources :users
  resources :githubs
  mount Sidekiq::Web => "/sidekiq"
end

app/views/layouts/shared/_logout_modal.html.erb
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel"><%= t "logout_modal_title" %></h5>
        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">×</span>
        </button>
      </div>
      <div class="modal-body"><%= t "logout_modal_content" %></div>
      <div class="modal-footer">
        <button class="btn btn-secondary" type="button" data-dismiss="modal"><%= t "cancel" %></button>
        <%= link_to t("log_out"), destroy_user_session_path, method: :delete, class: "btn btn-primary" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shared/_notifications.html.erb
<li class="nav-item dropdown no-arrow mx-1">
  <a class="nav-link dropdown-toggle" href="#" id="alertsDropdown"
    role="button" data-toggle="dropdown"aria-haspopup="true"
    aria-expanded="false">
    <i class="fas fa-bell fa-fw"></i>
    <% if @notifications.present? %>
      <span class="badge badge-danger badge-counter">
        <%= @notifications.unread.size %>+
      </span>
    <% end %>
  </a>
  <div aria-labelledby="alertsDropdown"
    class="dropdown-list dropdown-menu dropdown-menu-right
           shadow animated--grow-in">
    <h6 class="dropdown-header">
      <%= t "alerts_center" %>
    </h6>
    <% @notifications&.each do |notification| %>
    <a class="dropdown-item d-flex align-items-center" href="<%= notify_path notification.id %>">
      <div>
        <div class="small text-gray-500"><%= notification.created_at %></div>
        <% if notification.read? %>
          <%= notification.msg %>
        <% else %>
          <span class="font-weight-bold"><%= notification.msg %></span>
        <% end %>
      </div>
    </a>
    <% end %>
  </div>
</li>

app/views/layouts/shared/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="<%= root_path %>">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3"><%= t "base_title" %></div>
  </a>
  <% if user_signed_in? %>
    <div class="sidebar-heading">
      <%= t "report" %>
    </div>
    <li class="nav-item <%= add_active_class new_report_path %>">
      <a class="nav-link" href="<%= new_report_path %>">
        <i class="fas fa-fw fa-chart-area"></i>
        <span><%= t("new_report") %></span>
      </a>
    </li>
    <li class="nav-item <%= add_active_class(reports_path) %>">
      <a class="nav-link" href="<%= reports_path %>">
        <i class="fas fa-fw fa-table"></i>
        <span><%= t("report_list") %></span></a>
    </li>
    <% if current_user.admin? %>
      <hr class="sidebar-divider d-none d-md-block">
        <div class="sidebar-heading">
          <%= t "department" %>
        </div>
      <li class="nav-item <%= add_active_class(new_relationship_path) %>">
        <a class="nav-link" href="<%= new_relationship_path %>">
          <i class="fas fa-fw fa-table"></i>
          <span><%= t "manager_user" %></span></a>
      </li>
      <% active_context = active_link?(includes: ["new_department_path", "departments_path"]) %>
      <li class="nav-item ">
        <a class="nav-link" href="#" data-toggle="collapse" data-target="#components" aria-expanded="true" aria-controls="components">
          <i class="fas fa-fw fa-cog"></i>
          <span><%= t("manager") %></span>
        </a>
        <div id="components" class="collapse show" aria-labelledby="headingTwo" data-parent="#accordionSidebar" style="">
          <div class="bg-white py-2 collapse-inner rounded">
          <%= active_link_to t("create_new_department"), new_department_path, class: 'collapse-item' %>
          <%= active_link_to t("departments_list"), departments_path, class: 'collapse-item' %>
          </div>
        </div>
      </li>
      <div class="sidebar-heading">
        <%= t "user" %>
      </div>
      <li class="nav-item <%= add_active_class new_user_path %>">
        <a class="nav-link" href="<%= new_user_path %>">
          <i class="fas fa-fw fa-chart-area"></i>
          <span><%= t "create_new_user" %></span>
        </a>
      </li>
      <li class="nav-item <%= add_active_class(users_path) %>">
        <a class="nav-link" href="<%= users_path %>">
          <i class="fas fa-fw fa-table"></i>
          <span><%= t "users_list" %></span></a>
      </li>
      <hr class="sidebar-divider d-none d-md-block">
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>
    <% end %>
  <% end %>
</ul>

app/views/layouts/shared/_topbar.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>
  <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
  </form>
  <ul class="navbar-nav ml-auto">
    <li class="nav-item dropdown no-arrow mx-1">
      <span class="nav-link dropdown-toggle">
        <%= link_to t("en"), locale: :en, class: "nav-link dropdown-toggle" %>
      </span>
    </li>
    <li class="nav-item dropdown no-arrow mx-1">
      <span class="nav-link dropdown-toggle">
        <%= link_to t("vi"), locale: :vi %>
      </span>
    </li>
    <% if user_signed_in? %>
      <%= render "layouts/shared/notifications" %>
      <div class="topbar-divider d-none d-sm-block"></div>
      <%= render "layouts/shared/user_nav" %>
    <% end %>
  </ul>
</nav>

app/views/layouts/shared/_user_nav.html.erb
<li class="nav-item dropdown no-arrow">
  <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
    <span class="mr-2 d-none d-lg-inline text-gray-600 small"><%= current_user.full_name %></span>
    <%= gravatar_for current_user, Settings.user.tiny_avatar_height, Settings.user.tiny_avatar_width, "rounded-circle" %>
  </a>
  <!-- Dropdown - User Information -->
  <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
    <a class="dropdown-item" href="<%= user_path current_user %>">
      <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
      <%= t "profile" %>
    </a>
    <a class="dropdown-item" href="<%= edit_user_path current_user %>">
      <i class="fas fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
      <%= t "settings" %>
    </a>
    <div class="dropdown-divider"></div>
    <a class="dropdown-item" href="destroy_user_session_path" data-toggle="modal" data-target="#logoutModal">
      <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
      <%= t "log_out" %>
    </a>
  </div>
</li>