config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "departments#index"
    resources :departments do
      resources :reports
    end
    resources :reports do
      member do
        put :approve
      end
    end
    resources :relationships, only: %i(new create destroy update)
    resources :comments
    resources :notifies, only: :show
  end
  devise_for :users
  resources :users
  resources :githubs
  mount Sidekiq::Web => "/sidekiq"
end

app/models/department.rb
class Department < ApplicationRecord
  UPDATEABLE_ATTRS = %i(name description avatar).freeze
  has_many :reports, dependent: :destroy
  has_many :relationships, dependent: :destroy
  has_many :users, through: :relationships
  has_one_attached :avatar

  validates :name, presence: true,
            length: {maximum: Settings.digits.length_50},
            uniqueness: {case_sensitive: true}

  validates :description, presence: true,
            length: {maximum: Settings.digits.length_255}

  validates :avatar,
            content_type: {in: Settings.image.accept_format,
                           message: I18n.t(".invalid_img_type")},
            size: {less_than: Settings.image.max_size.megabytes,
                   message: I18n.t(".invalid_img_size")}

  scope :sort_created_at, ->{order :created_at}

  scope :by_name, (lambda do |name|
    where("name LIKE (?)", "%#{name}%") if name.present?
  end)

  scope :by_description, (lambda do |description|
    where("description LIKE (?)", "%#{description}%") if description.present?
  end)

  def display_avatar width = Settings.gravatar.width_default,
    height = Settings.gravatar.height_default
    avatar.variant resize_to_limit: [width, height]
  end

  def add_user user
    users << user
  end
end

app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :authenticate_user!
  authorize_resource
  before_action :paginate_departments, only: :index
  before_action :find_department, except: %i(index new create)
  Pagy::DEFAULT[:items] = Settings.department.per_page

  def index; end

  def show
    @pagy, @users = pagy @department.users
  end

  def new
    @department = Department.new
  end

  def create
    @department = Department.new department_params
    if @department.save
      save_avatar
      flash[:success] = t ".create_department_message"
      redirect_to @department
    else
      flash.now[:danger] = t ".create_department_error"
      render :new
    end
  end

  def edit; end

  def update
    if @department.update(department_params)
      flash[:success] = t ".edit_success_message"
      redirect_to @department
    else
      flash.now[:danger] = t ".edit_failure_message"
      render :edit
    end
  end

  def destroy
    if @department.destroy
      flash[:success] = t ".deleted_message"
    else
      flash[:danger] = t ".delete_failed_message"
    end
    redirect_to departments_path
  end

  private

  def department_params
    params.require(:department).permit Department::UPDATEABLE_ATTRS
  end

  def save_avatar
    avatar = params[:department][:avatar]
    @department.avatar.attach(avatar) if avatar
  end

  def paginate_departments
    @pagy, @departments = pagy filter_department
  end

  def filter_department
    return Department.sort_created_at unless params[:filter]

    @departments = Department
                   .by_name(params[:filter][:name])
                   .by_description(params[:filter][:description])
                   .sort_created_at
  end

  def find_department
    @department = Department.find_by id: params[:id]
    return if @department

    flash[:danger] = t ".not_found"
    redirect_to root_path
  end
end

app/views/departments/_department.html.erb
<tr>
  <td>
    <%= department.id %>
  </td>
  <td><%= link_to department.name, department %></td>
  <td><%= l department.created_at, format: :standard %></td>
  <td><%= l department.updated_at, format: :standard %></td>
  <td>
    <% if current_user.admin? %>
      <%= link_to t("edit"), edit_department_path(department), class: "text-info" %>
    <% end %>
  </td>
  <td>
    <%= link_to t(".delete"), @department, method: :delete,
      data: { confirm: t(".delete_confirmation") }, class: "text-danger" %>
  </td>
</tr>

app/views/departments/_departments_filter.html.erb
<div class="card shadow mb-4">
  <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
    <h6 class="m-0 font-weight-bold text-primary"><%= t ".search_title" %></h6>
  </a>
  <div class="collapse show" id="collapseCardExample" style="">
    <div class="card-body">
      <%= form_tag departments_path, method: :get do %>
        <div class="input-group">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <%= text_field :filter, :name_search, value: params.dig(:filter, :name),
                         class: "form-control", placeholder: t(".name") %>
        </div>
        <div class="input-group mt-16">
          <span class="input-group-addon"><i class="glyphicon glyphicon-record"></i></span>
          <%= text_field :filter, :description_search, value: params.dig(:filter, :description),
                         class: "form-control", placeholder: t(".description") %>
        </div>
        <%= submit_tag t(".search"), class: "btn btn-success mt-16" %>
      <% end %>
    </div>
  </div>
</div>

app/views/departments/_form.html.erb
<div class="center-form">
  <%= form_for @department do |f| %>
    <%= render "shared/error_messages", object: @department %>
    <%= f.label :name %>
    <%= f.text_field :name, class: "form-control" %>
    <%= f.label :description %>
    <%= f.text_area :description, class: "form-control" %>
    <%= f.label :change_avatar, class: "mt-16" %>
    <div class="input-group">
      <div class="input-group-prepend">
        <span class="input-group-text" id="inputGroupFileAddon01"><%= t "upload"%></span>
      </div>
      <div class="custom-file">
        <%= f.file_field :avatar, class: "file" %>
        <label class="custom-file-label" for="department_avatar"><%= t "choose_file"%></label>
      </div>
    </div>
    <%= f.submit yield(:button_text), class: "btn btn-primary mt-16" %>
  <% end %>
</div>

app/views/departments/_user.html.erb
<tr>
  <td>
    <%= user.id %>
  </td>
  <td><%= link_to user.email, user %></td>
  <td><%= link_to user.full_name, user %></td>
  <td><%= show_role_name user, @department %></td>
  <td><%= l user.created_at, format: :standard %></td>
  <% if (current_user.admin? || user_manager?(current_user, @department)) && !current_user?(user) %>
    <td>
      <%= link_to t(".remove_user"), get_relationship(user, @department), method: :delete,
        data: { confirm: t(".delete_confirmation") }, class: "text-danger" %>
    </td>
    <td>
      <% if user_manager? user, @department%>
        <%= form_for(get_relationship(user, @department)) do |f| %>
          <%= hidden_field_tag :role, :employee %>
          <%= f.submit t(".remove_manager"), class: "btn btn-warning btn-sm" %>
        <% end %>
      <% else %>
        <%= form_for(get_relationship(user, @department)) do |f| %>
          <%= hidden_field_tag :role, :manager %>
          <%= f.submit t(".set_user_manager"), class: "btn btn-primary btn-sm" %>
        <% end %>
      <% end %>
    </td>
  <% else %>
    <td></td>
    <td></td>
  <% end %>
</tr>

app/views/departments/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".submit") %>
<h1 class="text-center"><%= t ".welcome" %></h1>
<%= render "form" %>

app/views/departments/index.html.erb
<% provide :title, t(".title") %>
<%= render("departments_filter") %>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= t ".title" %></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th><%= t ".id" %></th>
            <th><%= t ".department_name" %></th>
            <th><%= t ".date_created" %></th>
            <th><%= t ".last_updated" %></th>
            <th><%= t ".edit" %></th>
            <th><%= t ".delete" %></th>
          </tr>
        </thead>
        <tfoot>
          <tr>
            <th><%= t ".id" %></th>
            <th><%= t ".department_name" %></th>
            <th><%= t ".date_created" %></th>
            <th><%= t ".last_updated" %></th>
            <th><%= t ".edit" %></th>
            <th><%= t ".delete" %></th>
          </tr>
        </tfoot>
        <tbody>
          <%= render @departments %>
        </tbody>
      </table>
    </div>
  </div>
</div>
<%== pagy_bootstrap_nav @pagy %>

app/views/departments/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".submit") %>
<h1 class="text-center"><%= t ".welcome" %></h1>
<%= render "form" %>

app/views/departments/show.html.erb
<% provide :title, @department.name %>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= @department.name %></h6>
  </div>
  <div class="card-body">
    <div class="text-center">
      <%= gravatar_for @department, Settings.department.avatar_width, Settings.department.avatar_height, "img-fluid px-3 px-sm-4 mt-3 mb-4" %>
    </div>
    <p><%= t @department.description %></p>
  </div>
</div>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= "#{t(".total_member")} (#{@pagy.count})" %></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
        <thead>
          <tr>
            <th><%= t ".id" %></th>
            <th><%= t ".email" %></th>
            <th><%= t ".full_name" %></th>
            <th><%= t ".role" %></th>
            <th><%= t ".date_created" %></th>
            <th></th>
            <th></th>
          </tr>
        </thead>
        <tfoot>
            <tr>
              <th><%= t ".id" %></th>
              <th><%= t ".email" %></th>
              <th><%= t ".full_name" %></th>
              <th><%= t ".role" %></th>
              <th><%= t ".date_created" %></th>
              <th></th>
              <th></th>
            </tr>
        </tfoot>
        <tbody>
          <%= render partial: "user", collection: @users, as: :user %>
        </tbody>
      </table>
    </div>
  </div>
</div>