config/routes.rb
require "sidekiq/web"

Rails.application.routes.draw do
  scope "(:locale)", locale: /en|vi/ do
    root "departments#index"
    resources :departments do
      resources :reports
    end
    resources :reports do
      member do
        put :approve
      end
    end
    resources :relationships, only: %i(new create destroy update)
    resources :comments
    resources :notifies, only: :show
  end
  devise_for :users
  resources :users
  resources :githubs
  mount Sidekiq::Web => "/sidekiq"
end

app/models/report.rb
class Report < ApplicationRecord
  include CreateNotify

  UPDATEABLE_ATTRS = [:report_date, :today_plan, :today_work,
    :today_problem, :tomorow_plan,
    {comments_attributes: [:report_id, :description, :user_id]}].freeze

  belongs_to :from_user, class_name: User.name
  belongs_to :department
  has_many :comments, dependent: :destroy

  after_create :notify

  accepts_nested_attributes_for :comments, allow_destroy: true,
    reject_if: ->(attrs){attrs[:description].blank?}

  enum report_status: {unverifyed: 0, confirmed: 1}

  delegate :full_name, to: :from_user
  delegate :name, to: :department

  validates :report_date, presence: true

  validates :today_plan, presence: true,
            length: {maximum: Settings.digits.length_255}

  validates :today_work, presence: true,
            length: {maximum: Settings.digits.length_255}

  validates :today_problem, presence: true,
            length: {maximum: Settings.digits.length_255}

  validates :tomorow_plan, presence: true,
            length: {maximum: Settings.digits.length_255}

  scope :sort_created_at, ->{order :created_at}

  scope :by_department, (lambda do |department_name|
    if department_name.present?
      Report.joins(:department).where("name LIKE (?)", "%#{department_name}%")
    end
  end)

  scope :by_name, (lambda do |name|
    if name.present?
      Report.joins(:from_user).where("full_name LIKE (?)", "%#{name}%")
    end
  end)

  scope :by_id, (lambda do |id|
    where(id: id) if id.present?
  end)

  scope :by_created_at, (lambda do |created_at|
    where(created_at: created_at) if created_at.present?
  end)

  scope :by_report_date, (lambda do |report_date|
    where(report_date: report_date) if report_date.present?
  end)

  scope :for_manager, (lambda do |department_id|
    where(department_id: department_id) if department_id
  end)

  scope :for_employee, (lambda do |user_id|
    where(from_user_id: user_id) if user_id
  end)

  scope :by_status, (lambda do |status|
    where(report_status: status) if status
  end)

  def approve action
    return unverifyed! if action.eql? Settings.report.unverifyed

    confirmed! if action.eql? Settings.report.confirmed
  end

  private

  def notify
    create_notify from_user_id, I18n.t("to_report"),
                  routes.report_path(id: id)
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  authorize_resource
  before_action :find_department, except: %i(destroy new index)
  before_action :paginate_reports, only: :index
  before_action :find_report, except: %i(index new create)
  before_action :check_ownership, :require_unverifyed, only: %i(update destroy)
  before_action :prepare_report, only: :create
  before_action :find_accessible_department, only: %i(new create edit)

  def index
    @filter = params[:filter]
  end

  def show
    @comments = @report.comments.sort_created_at
    @comment = @report.comments.build
  end

  def new
    @report = Report.new
    @report.comments.build
  end

  def create
    if @report.save
      flash[:success] = t ".create_report_message"
      redirect_to root_path
    else
      flash.now[:danger] = t ".create_report_error"
      render :new
    end
  end

  def edit; end

  def update
    if @report.update report_params
      flash[:success] = t ".edit_success_message"
      redirect_to department_reports_path(@report.department_id)
    else
      flash.now[:danger] = t ".edit_failure_message"
      render :edit
    end
  end

  def destroy
    if @report.destroy
      flash[:success] = t ".deleted_message"
    else
      flash[:danger] = t ".delete_failed_message"
    end
    redirect_to department_reports_path(@report.department_id)
  end

  def approve
    if @report.approve params[:status]
      flash[:success] = t ".update_success"
    else
      flash[:danger] = t ".update_failure"
    end
    redirect_to root_path
  end

  private

  def report_params
    params.require(:report).permit Report::UPDATEABLE_ATTRS
  end

  def find_department
    @department = Department.find params[:department_id]
  end

  def find_report
    @report = Report.find params[:id]
  end

  def paginate_reports
    @pagy, @reports = pagy find_all_reports, items: Settings.report.per_page
  end

  def filter_report
    filter = params[:filter]
    return @reports unless filter

    @reports = @reports.by_id(filter[:id])
                       .by_department(filter[:department])
                       .by_name(filter[:name])
                       .by_created_at(filter[:date_created])
                       .by_report_date(filter[:date_reported])
                       .by_status(filter[:status])
                       .sort_created_at
  end

  def find_all_reports
    @reports = Report.accessible_by(current_ability)
                     .includes([:department, :from_user])
    filter_report
  end

  def check_ownership
    return if @report.from_user_id.eql? current_user.id

    flash[:danger] = t "ownership_error"
    redirect_to root_path
  end

  def require_unverifyed
    return if @report.unverifyed?

    flash[:danger] = t "unverifyed_error"
    redirect_to root_path
  end

  def prepare_report
    @report = @department.first.reports.build report_params
              .merge from_user_id: current_user.id
  end

  def find_accessible_department
    @departments = Department.accessible_by current_ability
  end
end

app/helpers/reports_helper.rb
module ReportsHelper
  def manager_role? report
    current_user.admin? || user_manager?(current_user, report.department)
  end
end

app/views/reports/_all_comments.html.erb
<div class="row">
  <div class="detailBox col-md-12">
    <div class="titleBox">
      <label><%= t ".comment_box" %></label>
    </div>
    <div class="actionBox">
      <ul class="commentList">
        <%= render @comments %>
      </ul>
      <% if @report.unverifyed? %>
        <%= render "new_comment" %>
      <% end %>
    </div>
  </div>
</div>
 <!-- Modal -->
<%= form_tag comment_path, method: :put, remote: true do %>
  <div class="modal fade" id="myModal" role="dialog">
    <div class="modal-dialog top-30p">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">t ".edit_comment"</h4>
        </div>
        <div class="modal-body">
          <input type="hidden" id="comment_id" name="comment_id">
          <%= text_area_tag :comment_modal_text, nil, class: "form-control w-100 comment_modal_text" %>
        </div>
        <div class="modal-footer">
          <input type="submit" class="btn btn-default" value="Save"/>
        </div>
      </div>
    </div>
  </div>
<% end %>
<%= javascript_pack_tag "comment" %>

app/views/reports/_all_reports.html.erb
<div>
  <h4>
    <%= t ".all_report" %>
    (<span>
      <%= @reports.size %>
    </span>)
  </h4>
</div>
<%= form_tag "#", method: :put, remote: true, id: "checkbox-form" do %>
  <table class="table table-hover">
    <thead>
      <tr>
        <th><%= t ".ID" %></th>
        <th><%= t ".department" %></th>
        <th><%= t ".name" %></th>
        <th><%= t ".date_reported" %></th>
        <th><%= t ".date_created" %></th>
        <th><%= t ".status" %></th>
        <th><%= t ".action" %></th>
      </tr>
    </thead>
    <tbody>
      <%= render @reports %>
    </tbody>
  </table>
<% end %>

app/views/reports/_comment_fields.html.erb
<div class="nested-fields">
  <%= f.label :your_comment %>
  <%= f.text_field :description, class: "form-control", placeholder: t(".your_comment") %>
  <%= f.hidden_field :user_id, value: current_user.id %>
  <%= link_to_remove_association t(".remove_comment"), f, class: "text-danger mt-16" %>
</div>

app/views/reports/_filter_form.html.erb
<div class="card shadow mb-4">
  <a href="#collapseCardExample" class="d-block card-header py-3" data-toggle="collapse" role="button" aria-expanded="true" aria-controls="collapseCardExample">
    <h6 class="m-0 font-weight-bold text-primary"><%= t ".search_title" %></h6>
  </a>
  <div class="collapse show" id="collapseCardExample" style="">
    <div class="card-body">
      <%= form_tag reports_path, method: :get do %>
        <div class="input-group col-md-4">
          <span class="input-group-addon"><i class="glyphicon glyphicon-star"></i></span>
          <%= text_field :filter, :id, value: params.dig(:filter, :id), class: "form-control", placeholder: t(".id") %>
        </div>
        <div class="input-group mt-16 col-md-6">
          <span class="input-group-addon"><i class="glyphicon glyphicon-user"></i></span>
          <%= text_field :filter, :name, value: params.dig(:filter, :name), class: "form-control", placeholder: t(".name") %>
        </div>
        <div class="input-group mt-16 col-md-4">
          <span class="input-group-addon"><i class="glyphicon glyphicon-record"></i></span>
          <%= date_field :filter, :date_reported, value: params.dig(:filter, :date_reported), class: "form-control", placeholder: t(".date_reported") %>
        </div>
        <div class="input-group mt-16 col-md-5">
          <span class="input-group-addon"><i class="glyphicon glyphicon-edit"></i></span>
          <%= select :filter, :status, Report.report_statuses.keys, {include_blank: true, selected: (@filter[:status] if @filter)}, class: "form-control" %>
        </div>
        <%= submit_tag t(".search"), class: "btn btn-success mt-16" %>
      <% end %>
    </div>
  </div>
</div>

app/views/reports/_form.html.erb
<div class="center-form">
  <%= form_for @report do |f| %>
    <%= render "shared/error_messages", object: @report %>
    <%= f.label :assign_to %><span class="text-danger"> *</span>
    <%= collection_select :department_id, nil, @departments, :id, :name, options ={},
                        class: "js-example-basic-single form-control" %>
    <%= f.label :report_date %><span class="text-danger"> *</span>
    <%= f.date_field :report_date, class: "form-control" %>
    <%= f.label :today_plan %><span class="text-danger"> *</span>
    <%= f.text_area :today_plan, class: "form-control" %>
    <%= f.label :today_work %><span class="text-danger"> *</span>
    <%= f.text_area :today_work, class: "form-control" %>
    <%= f.label :today_problem %><span class="text-danger"> *</span>
    <%= f.text_area :today_problem, class: "form-control" %>
    <%= f.label :tomorow_plan %><span class="text-danger"> *</span>
    <%= f.text_area :tomorow_plan, class: "form-control" %>
    <div class="links">
      <%= link_to_add_association t(".add_comment"), f, :comments, class: "mt-16" %>
    </div>
    <%= f.submit yield(:button_text), class: "btn btn-primary mt-16 form-control" %>
  <% end %>
</div>

app/views/reports/_new_comment.html.erb
<%= form_for @comment do |f| %>
  <%= render "shared/error_messages", object: @comment %>
  <div class="form-inline">
    <div class="form-group">
      <%= f.text_field :description, class: "form-control", placeholder: t(".your_comment") %>
      <%= hidden_field_tag :report_id, @report.id %>
    </div>
    <div class="form-group">
      <%= f.submit t(".add"), class: "btn btn-default" %>
    </div>
  </div>
<% end %>

app/views/reports/_report.html.erb
<tr>
  <td><%= report.id %></td>
  <td><%= report.department.name %></td>
  <td><%= link_to report.from_user.full_name, user_path(report.from_user.id) %></td>
  <td><%= l report.report_date, format: :standard %></td>
  <td><%= l report.created_at, format: :standard %></td>
  <td><span class=<%= report.confirmed? ? "text-info" : "text-danger" %>><%= report.report_status %></span></td>
  <td>
    <%= link_to t(".detail"), department_report_path(report.department_id, report.id) %>
  </td>
</tr>

app/views/reports/_view_report.html.erb
<%= form_for @report do |f| %>
  <%= render "shared/error_messages", object: @report %>
  <%= f.label :report_date %>
  <%= f.date_field :report_date, class: "form-control", disabled: true %>
  <%= f.label :today_plan %>
  <%= f.text_area :today_plan, class: "form-control", disabled: true %>
  <%= f.label :today_work %>
  <%= f.text_area :today_work, class: "form-control", disabled: true %>
  <%= f.label :today_problem %>
  <%= f.text_area :today_problem, class: "form-control", disabled: true %>
  <%= f.label :tomorow_plan %>
  <%= f.text_area :tomorow_plan, class: "form-control", disabled: true %>
  <% if @report.unverifyed? && @report.from_user.eql?(current_user) %>
    <%= link_to t(".edit"), edit_department_report_path(@report.department.id, @report.id), class: "btn btn-primary mt-16 float-right" %>
    <%= link_to t(".delete"), @report, method: :delete,
      data: { confirm: t(".delete_confirmation") }, class: "btn btn-danger mt-16 float-right mr-8" %>
  <% end %>
  <% if manager_role? @report %>
    <% if @report.unverifyed? %>
      <%= link_to t(".approve"), approve_report_path(@report.id, status: :confirmed, department_id: @department.id), method: :put,
        class: "btn btn-primary mt-16 float-right" %>
    <% else %>
      <%= link_to t(".cancel"), approve_report_path(@report.id, status: :unverifyed, department_id: @department.id), method: :put,
        class: "btn btn-danger mt-16 float-right mr-8" %>
    <% end %>
  <% end %>
<% end %>

app/views/reports/edit.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".submit") %>
<h1><%= t ".welcome" %></h1>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "form" %>
  </div>
</div>

app/views/reports/index.html.erb
<% provide :title, t(".title") %>
<%= render "filter_form" %>
<div class="card shadow mb-4">
  <div class="card-header py-3">
    <h6 class="m-0 font-weight-bold text-primary"><%= t ".title" %></h6>
  </div>
  <div class="card-body">
    <div class="table-responsive">
      <%= form_tag "#", method: :put, remote: true, id: "checkbox-form" do %>
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th><%= t ".ID" %></th>
              <th><%= t ".department" %></th>
              <th><%= t ".name" %></th>
              <th><%= t ".date_reported" %></th>
              <th><%= t ".date_created" %></th>
              <th><%= t ".status" %></th>
              <th><%= t ".action" %></th>
            </tr>
          </thead>
          <tfoot>
              <tr>
                <th><%= t ".ID" %></th>
                <th><%= t ".department" %></th>
                <th><%= t ".name" %></th>
                <th><%= t ".date_reported" %></th>
                <th><%= t ".date_created" %></th>
                <th><%= t ".status" %></th>
                <th><%= t ".action" %></th>
              </tr>
          </tfoot>
          <tbody>
            <%= render @reports %>
          </tbody>
        </table>
      <% end %>
    </div>
  </div>
</div>
<%== pagy_bootstrap_nav @pagy %>

app/views/reports/new.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".submit") %>
<h1 class="text-center"><%= t ".welcome" %></h1>
<%= render "form" %>

app/views/reports/show.html.erb
<% provide :title, t(".title") %>
<% provide :button_text, t(".submit") %>
<div class="row">
  <aside class="col-md-12">
    <section class="user_info">
      <h1>
        <%= gravatar_for @report.from_user, Settings.user.small_avatar_height, Settings.user.small_avatar_height %>
        <%= @report.from_user.full_name %>
      </h1>
    </section>
  </aside>
</div>
<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= render "view_report" %>
  </div>
</div>
<%= render "all_comments" %>